name: shodana_reader
description: A new Flutter application for reading ebooks.
publish_to: 'none'
version: 0.1.0+172

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For Architecture
  beamer: ^0.14.1
  hooks_riverpod: ^0.14.0+4
  responsive_builder: ^0.4.1
  multi_screen_layout: ^2.0.0
  intl: ^0.17.0
  i18n_extension: ^4.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  # For backend
  appwrite: ^0.7.1
  flappwrite_account_kit:
    git: https://github.com/lohanidamodar/flappwrite_account_kit

  # For realtime:
  # appwrite:
  #   git:
  #     url: https://github.com/appwrite/sdk-for-flutter
  #     ref: feat-realtime

  # flappwrite_account_kit:
  #   git: https://github.com/getBoolean/flappwrite_account_kit
  #   # path: ../flappwrite_account_kit

  # For login
  email_validator: ^2.0.1
  sign_button: ^2.0.1
  flutter_signin_button: ^2.0.0

  # For books
  file_picker: ^4.0.0
  epubx: ^3.0.0-dev.3
  path_provider: ^2.0.1 
  file_selector: ^0.8.2
  file_selector_windows: ^0.0.2+1
  file_selector_linux: ^0.0.2+1
  # TODO: Add file_selector_macos https://pub.dev/packages/file_selector_macos

  # For Database
  flutter_persistent_queue:
    git: https://github.com/getBoolean/flutter_persistent_queue
  uuid: ^3.0.4

  # For Key-Value local storage
  shared_preferences: ^2.0.5

  # Convert between Enum and String
  enum_to_string: ^2.0.1

  # For UIs
  cupertino_icons: ^1.0.3
  smart_select: ^4.3.2
  adaptive_theme: ^2.2.0
  flex_color_scheme: ^3.0.1
  flutter_native_splash: ^1.2.1
  material_floating_search_bar: ^0.3.4
  cached_network_image: ^3.1.0
  implicitly_animated_reorderable_list: ^0.4.0
  pull_to_refresh: ^2.0.0
  community_material_icon: ^5.9.55
  flutter_staggered_grid_view: ^0.4.0
  reorderable_grid_view: ^1.1.0

  # For Utilities
  url_launcher: ^6.0.9
  package_info_plus: ^1.0.1
  device_info: ^2.0.0
  clipboard: ^0.1.3
  permission_handler: ^8.1.4+2
  flutter_lints: ^1.0.4
  equatable: ^2.0.3

  # For scripts
  dart_appwrite: ^0.7.0
  envify: ^2.0.2
  # mockito: ^5.0.14

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any
  envify_generator: ^2.0.0
  build_runner: ^2.1.1
  flutter_gen_runner: ^3.1.1
  flutter_launcher_icons: ^0.9.0
  hive_generator: ^1.1.0

# Uncomment the flutter_icons section when adding an icon, then run
# flutter pub run flutter_launcher_icons:main

#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/icon/icon.png"

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/svgs/