name: shodana_reader
description: A new Flutter application for reading ebooks.
publish_to: 'none'
version: 0.0.2+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For Architecture
  beamer: ^0.13.2
  flutter_hooks: ^0.16.0
  hooks_riverpod: ^0.14.0+3
  responsive_builder: ^0.4.1
  multi_screen_layout: ^2.0.0
  intl: ^0.17.0

  # For backend
  appwrite: ^0.6.0
  flappwrite_account_kit:
    git: https://github.com/lohanidamodar/flappwrite_account_kit

  # For books
  file_picker: ^3.0.1
  epubx: ^3.0.0-dev.3
  path_provider: ^2.0.1

  # For Key-Value local storage
  shared_preferences: ^2.0.5

  # Convert between Enum and String
  enum_to_string: ^2.0.1

  # For UIs
  cupertino_icons: ^1.0.3
  smart_select: ^4.3.2
  adaptive_theme: ^2.2.0
  flex_color_scheme: ^2.1.1
  flutter_native_splash: ^1.1.8+4

  # For Utilities
  get: ^4.1.4
  url_launcher: ^6.0.3
  package_info_plus: ^1.0.1
  device_info: ^2.0.0
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons: ^0.9.0

# Uncomment the flutter_icons section when adding an icon, then run
# flutter pub run flutter_launcher_icons:main

#flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/icon/icon.png"

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
