name: shodana_reader
description: A new Flutter application for reading ebooks.
publish_to: 'none'
version: 0.1.0+173

environment:
  sdk: '>=2.12.0 <3.0.0'

dependency_overrides:
  appwrite: ^1.0.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For Architecture
  beamer: ^0.14.1
  hooks_riverpod: ^1.0.0-dev.7
  responsive_builder: ^0.4.1
  multi_screen_layout: ^2.0.0
  intl: ^0.17.0
  i18n_extension: ^4.1.0
  dartz: ^0.10.0

  # For Key-Value local storage
  shared_preferences: ^2.0.5

  # For Database
  flutter_persistent_queue:
    git: https://github.com/getBoolean/flutter_persistent_queue
  uuid: ^3.0.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  # For backend
  appwrite: ^1.0.2
  flappwrite_account_kit:
    git: https://github.com/lohanidamodar/flappwrite_account_kit

  # For login
  email_validator: ^2.0.1
  sign_button: ^2.0.1
  flutter_signin_button: ^2.0.0

  # For books
  file_picker: ^4.0.0
  epubx: ^3.0.0-dev.3
  path_provider: ^2.0.1
  file_selector: ^0.8.2
  file_selector_windows: ^0.0.2+1

  # Convert between Enum and String
  enum_to_string: ^2.0.1

  # For UIs
  cupertino_icons: ^1.0.3
  smart_select: ^4.3.2
  adaptive_theme: ^2.2.0
  flex_color_scheme: ^3.0.1
  material_floating_search_bar: ^0.3.4
  cached_network_image: ^3.1.0
  implicitly_animated_reorderable_list: ^0.4.0
  pull_to_refresh: ^2.0.0
  community_material_icon: ^5.9.55
  flutter_staggered_grid_view: ^0.4.0
  reorderable_grid_view: ^1.1.0
  transparent_image: ^2.0.0
  # TODO: Add ability to drag files into app
  # native_draggable:
  #   # git: https://github.com/getBoolean/native_draggable
  #   path: ../native_draggable

  # For Utilities
  url_launcher: ^6.0.9
  package_info_plus: ^1.0.1
  device_info: ^2.0.0
  clipboard: ^0.1.3
  permission_handler: ^8.1.4+2
  equatable: ^2.0.3
  logger: ^1.1.0

  # For building windows installer
  msix: ^2.1.3

  # For tests
  # mockito: ^5.0.14

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: any
  build_runner: ^2.1.1
  flutter_gen_runner: ^3.1.1
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.2.3
  hive_generator: ^1.1.0
  flutter_lints: ^1.0.4

# Uncomment the flutter_icons section when adding an icon, then run
# flutter pub run flutter_launcher_icons:main

# flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/icon/icon.png"

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/svgs/

# For building for windows
# flutter build windows
# flutter pub run msix:create
msix_config:
  display_name: Shodana Reader
  publisher_display_name: Shodana Studio
  identity_name: app.ShodanaStudio.ShodanaReader
  msix_version: 0.1.0.0
  languages: en-us
  architecture: x64
  file_extension: .epub
  capabilities: internetClient,documentsLibrary
  store: false